# Change these first
owner: crileiton # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repositoryy

sites:
  - name: QB-Dev
    url: $URL_QB_DEV
    expectedStatusCodes:
      - 200
  - name: QB-QA
    url: $URL_QB_QA
    expectedStatusCodes:
      - 200
  - name: QB-Production
    url: $URL_QB_PROD
    expectedStatusCodes:
      - 200
  - name: PW-Dev
    url: $URL_PW_DEV
    expectedStatusCodes:
      - 200
  - name: PW-QA
    url: $URL_PW_QA
    expectedStatusCodes:
      - 200
  - name: Test Broken Site 8
    url: https://cradqqqssanleitsaasnnnon.com/applee
    expectedStatusCodes:
      - 200

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitoring - Cristian Leiton Valencia
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO
  
  #light,dark,night,ocean
  theme: night
i18n:
  activeIncidents: Incidentes activos
  allSystemsOperational: Todos los sistemas están operativos
  liveStatus: Estado en vivo
  
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
